### ISSUE TITLE
Custom Things oredict names are to long for digital miner

### ISSUE THREAD

**Issue by tjsd** [TPPIDev/TestPackPleaseIgnore2#155]
so, I was looking for some Tetrahedrite, and in the configs it is like this:
oreDictNames:[ "oreTetrahedrite" ]¨

but in the digitalminer I can only type in: oreTetrahedr
and it stops. So I cant go look for it.

**Comment by UndeadZeratul** [comment]
You should be able to do wildcards, like oreTetrahed*, or even oreTetra* since I don't think any other ores share the beginning of the word "Tetra".

you could do the same thing for dense ores; if you want to grab every single dense ore, no matter which one it is, just search for denseore*.

And if you just want any and all ores nearby, just search for ore*.
