### ISSUE TITLE
Add Gendustry to deal with bees

### ISSUE THREAD

**Issue by tjsd** [TPPIDev/TestPackPleaseIgnore2#170]
First of, normal forestry bee hives are super rare. You find magic bees all over the place.

With the current addons there are no alternative way to deal with bees then normal apiaries and eventually alveiaries. Gendustry would be greatly appreciated.

**Comment by Iwerks** [comment]
I requested this to be removed early on in the pack because I made yellorite bees in less than 30 minutes with perfect stats. Also because it would be extremely hard to balance and is quite frankly the most over-powered pile of bullshit in the world. This pack is balance not free unlimited resources. LEARN TO BEE AND WORK FOR IT.

**Comment by tjsd** [comment]
to be fair I didnt know about the genetics addon that binnie has added. Also I closed the case because nut and fako explained why it was like it was.
