### ISSUE TITLE
Iridium Ore currently unobtainable?

### ISSUE THREAD

**Issue by FlaxseedMC** [TPPIDev/TestPackPleaseIgnore2#215]
(Post GT-removal)

Unless I'm being stupid; it appears that IC2 Iridium Ore (4130) is currently unobtainable, and therefore cannot be scanned for production with UU-matter.

Whilst the dust is obtainable from the AOBTD block; Iridium Ore (6584) or the Nether Ores block; Nether Iridium Ore (1995:3) through processing with a variety of machines - the ore itself cannot be obtained. The AOBTD block is also not placeable in the world but this is secondary and probably intended.

This prevents the construction/use of most of the machines in Advanced Solar Panels, as Iridium Reinforced Plate (4131) can only be made using the IC2 Ore.

**Comment by wha-ha-ha** [comment]
I'm pretty sure in vanilla IC2 iridium ore as a block doesn't spawn in-world and instead you find iridium ore "drops" (so to speak) in dungeon chests instead.

This issue is a non-issue if this is the case.

**Comment by FakoTheGreat** [comment]
As far as I know, you're correct wha-ha-ha. However, it's worth noting that Another One Bites the Dust removes any means to process Iridium Ore (obtained from a mining laser or somesuch) into standard Iridium, as it makes even smelting it in a furnace provide the Iridium Bar from Advanced Solar Panels.

Because of this, I'll put a recipe in TPPI-Tweaks to allow crafting the Iridium Reinforced Plate with Iridium Bars.  The Bar itself is normally crafted by compressing iridium (with a 1:1 output) anyways, so it's not a drastic change.

**Comment by FakoTheGreat** [comment]
Recipe in place, with config option to disable if not wanted.
