### ISSUE TITLE
Osmium Texture Not Included/Broken

### ISSUE THREAD

**Issue by esKaayY** [TPPIDev/TestPackPleaseIgnore2#233]
As title says.

**Comment by capSAR273** [comment]
Would this just require the texture being added into the tweaks resource folder?

**Comment by mrgreenacid** [comment]
Confirmed, http://i.imgur.com/RP19XHH.png.  Too lazy to go find where the texture is and change configs ATM.

**Comment by capSAR273** [comment]
Woops, I was checking the wrong config, gotta look at the base block texture name instead.

**Comment by capSAR273** [comment]
From the DenseOres config: S:baseBlockTexture=mekanism:oreOsmium, I think this has to be changed to Osmiumore as per the texture's name in the assets folder.

**Comment by UndeadZeratul** [comment]
I was going to suggest that maybe it's because osmium is a 32x32 texture masquerading as a 16x16, but then again so is yellorite; Yellorite works as a dense ore, right?  Can't confirm at this time, but if memory serves me well, it should.

**Comment by capSAR273** [comment]
Yes Yellorite has a dense ore block, I was comparing it to Osmium because they are configured about the same way. I just cant figure out why Osmium won't find the texture :/

**Comment by UndeadZeratul** [comment]
Well that's what I mean; Yellorite ore is another case where it's a 32x32 texture that looks like a 16x16 one, which should cause an issue for dense ores.  Since it looks fine as a dense ore, then I don't know what the issue is for Osmium.

I do _vaguely_ remember tema talking about how the images were saved, maybe Mekanism saves their texture files oddly, and it's causing issues with dense ores?

**Comment by TehNut** [comment]
Something @esKaayY happened to leave out is that we've *already fixed this*. We just forgot to ship it.
