### ISSUE TITLE
Wormwood uncraftable

### ISSUE THREAD

**Issue by Cyrakrum** [TPPIDev/TestPackPleaseIgnore2#292]
In order to craft wormwood from witchery wheat must be right clicked with a mutating sprig but because of ttcore that becomes impossible. Ideally it'd be nice if ttcore had a blacklist which let there be specified items that did not cause the replanting effect.

**Comment by Cadfael221** [comment]
Hi! I'm using TPPI2 v 1.1, and unfortunately, I am having the same issue. It's preventing me from progressing any further in the witchery line, because I need wormwood in order to do any summoning. Was there a way to correct this? I see that this was closed, but I didn't know if there was a resolution planned.

**Comment by tterrag1098** [comment]
It's been resolved in newer ttCore versions. If you are desparate you can update the mod manually. The update will be included in the next TPPI update.
